### PR TITLE
added feature to move to some other page initially

### PR DESCRIPTION
**Pull request by tristola**
I have an implementation where I have smaller thumbnails, where you select what page you want to view and view details on the viewpager. Initial page is needed as a property, after that the navigation is given to viewpager.

### CODE REVIEW

**Comment by FMCorz** [comment]
This would fix #43.

Note, your patch does not meet the same coding style as the file. Also, you probably want to add the property to PropTypes which would ensure that the value is a `Number`.

**Comment by tristola** [comment]
Made the changes to coding style and added to the proptypes.
This pager worked nicely on a tablet app, with full screen paging with a scrollview (on android). 

If you have suggestions how to do the initialPage without the movePage function, that would be great. I had only limited time to try to figure this out.

**Comment by FMCorz** [comment]
Hi Tristola,

In case you did not notice, I am not the author, nor maintainer, of this package. I just happen to need the same feature as the one in your pull request. I haven't had a chance to look at how to achieve it so much, when I tried myself to set the initialPage I encountered some weird behaviours happening due to the recycling of the views. I'll have a go at your patch and let you know how it works for me.

**Comment by tristola** [comment]
I also had problems initially, and this was the nicest way i could make it work. it is not optimal since it will do an animation when starting the component. This was good enough for the project I was working on. I was hoping for some feedback from the maintainer, but no luck so far.

**Comment by FMCorz** [comment]
@tristola, seeing the animation was not an option for me, so I gave it a go. Would you mind throwing an eye at my patch to see what you think of it?

https://github.com/race604/react-native-viewpager/compare/master...FMCorz:initial-page?w=1

**Pull request merged**
