### PR TITLE
fixed:解决当viewpager在navigator中相互冲突的情况, resolve confict gesture viewpag…

### PR DESCRIPTION
**Pull request by hufeng**
…e and navigator
image

image

### CODE REVIEW

**Comment by hufeng** [comment]
解决可能和Touchable***的时间冲突。

**Comment by race604** [comment]
非常感谢

**Comment by FMCorz** [comment]
I'd have to test this patch but it may cause a regression for me if the pager always captures the gestures.

**Comment by race604** [comment]
Thank you @FMCorz . This is indeed a problem, we can always return `false` to capture the touch gesture. Maybe we can return `false` when in dragging?

**Comment by FMCorz** [comment]
Maybe we do not need to fix this as the navigator module has been deprecated in recent version of React. Or so I think.

**Comment by race604** [comment]
I agree. I revert this commit until we found better solution for this problem.

**Pull request merged**
